### PR TITLE
Enable iframe embeds

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**

### CODE REVIEW

**Comment by jacob-ebey** [comment]
Got some weird double scrolling going in the blog post page with the iframe embeds.

**Review by jacob-ebey — COMMENTED** [review]
Got some weird double scrolling going in the blog post page with the iframe embeds.

**Comment by ScriptedAlchemy** [comment]
> Got some weird double scrolling going in the blog post page with the iframe embeds.

Yeah the iframe is a variable height so two scrollbar appears for a short amount of time then it takes over on the iframe :P

**Comment by jacob-ebey** [comment]
> > Got some weird double scrolling going in the blog post page with the iframe embeds.
> 
> Yeah the iframe is a variable height so two scrollbar appears for a short amount of time then it takes over on the iframe :P

The double scrollbars remain on windows chrome.

image

**Comment by ScriptedAlchemy** [comment]
Add, youve got a mouse plugged in. Ill look at hiding the iframe scroll bar if possible

**Pull request closed without merging**
